// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/breadcrumb.vue')['default'];
    Editor: typeof import('./src/components/markdown/editor.vue')['default'];
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    Icon: typeof import('./src/components/icon.vue')['default'];
    JcButton: typeof import('./src/components/form/jc-button.vue')['default'];
    JcInput: typeof import('./src/components/form/jc-input.vue')['default'];
    JcLink: typeof import('./src/components/form/jc-link.vue')['default'];
    Notification: typeof import('./src/components/notification.vue')['default'];
  }
}

export {};
