// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default'];
    JcButton: typeof import('./../src/components/jc/button.vue')['default'];
    JcInput: typeof import('./../src/components/jc/input.vue')['default'];
    JcLink: typeof import('./../src/components/jc/link.vue')['default'];
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default'];
    Notification: typeof import('./../src/components/notification.vue')['default'];
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default'];
  }
}

export {};
